name: Manual macOS Build

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.12"  # или твоя версия

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          # Запуск PyInstaller из корня проекта, где лежит main.py
          pyinstaller \
            --noconfirm \
            --onedir \
            --windowed \
            --name "ScoreBoard_2" \
            --icon "images/app_logo.icns" \
            --add-data "pdf_editor:pdf_editor" \
            --add-data "images:images" \
            main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreBoard2-macOS-build
          path: dist/**
